### ISSUE TITLE
SmsAutoFill().listenForCode() does not work 

### ISSUE THREAD

**Issue by basnetjiten** [jaumard/sms_autofill#152]
cannot listen for sms code. It used to work on previous version. SmsAutoFill().listenForCode()

**Comment by shivams1110** [comment]
@basnetjiten I was facing same issue, make sure appsignature value is for release build not in debug build 
I fork this package and change it previous
it is working fine in android. 

```
sms_autofill:
    git:
      url: git@github.com:shivams1110/sms_autofill.git
      ref: master # branch name

```

try this
